language: crystal
install:
  - crystal deps
script:
  - crystal spec
  # Make sure everything works even without LuckyMigrator
  - crystal spec -D without-migrator
  - crystal tool format spec src --check
  - shards build
  - bin/ameba
